# Generated by Django 3.1.1 on 2021-02-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asft_core', '0003_auto_20210126_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default-avatar.png', upload_to='media_pfp'),
        ),
    ]
