# Generated by Django 3.1.1 on 2021-02-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asft_core', '0004_auto_20210204_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default-avatar_qdntfa.png', upload_to='media_pfp'),
        ),
    ]
